services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    command: --transaction-isolation=READ-COMMITTED --max_allowed_packet=256M
    volumes:
      - ./mysql-data:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    expose:
      - "80"
      - "8082"
    volumes:
      - ./seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
      - ./entrypoint.sh:/etc/my_init.d/99_fix_static_assets.sh:ro
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_ROOT_PASSWORD}  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=${TIME_ZONE}  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD} # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME} # Hostname only, without http:// or https://.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

  caddy:
    image: caddy:2
    container_name: seafile-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/Caddyfile.selfsigned:/etc/caddy/Caddyfile.selfsigned:ro
      - ./ssl:/etc/caddy/certs:ro
      - ./seafile-data/seafile/seafile-server-latest/seahub/media:/srv/media:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - seafile
    networks:
      - seafile-net

networks:
  seafile-net:

volumes:
  caddy-data:
  caddy-config:
